// WiFiConfig.example.h

#define WIFI_SSID "YOUR_WIFI_SSID"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"
#define FIREBASE_HOST "YOUR_FIREBASE_DB_URL"
#define FIREBASE_AUTH "YOUR_FIREBASE_AUTH_TOKEN"
#define BACKEND_URL "http://YOUR_BACKEND_SERVER_IP:5000/recognize"